backend:
  name: github
  repo: Max-McKone/hemshorn.com
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "German Homepage"
        name: "german_index"
        file: "de/index.html"
        fields:
          - label: "Hero Quote 1"
            name: "hero_quote_1"
            widget: "string"
          - label: "Hero Text 1"
            name: "hero_text_1"
            widget: "text"
          - label: "Hero Quote 2"
            name: "hero_quote_2"
            widget: "string"
          - label: "Hero Text 2"
            name: "hero_text_2"
            widget: "text"
          - label: "Hero Quote 3"
            name: "hero_quote_3"
            widget: "string"
          - label: "Hero Text 3"
            name: "hero_text_3"
            widget: "text"
          - label: "Main Content Paragraph 1"
            name: "main_content_1"
            widget: "text"
          - label: "Main Content Paragraph 2"
            name: "main_content_2"
            widget: "text"
          - label: "Main Content Paragraph 3"
            name: "main_content_3"
            widget: "text"
          - label: "Main Content Paragraph 4"
            name: "main_content_4"
            widget: "text"
          - label: "Contact Phone"
            name: "contact_phone"
            widget: "string"
          - label: "Contact Email"
            name: "contact_email"
            widget: "string"
      - label: "English Homepage"
        name: "english_index"
        file: "en/index.html"
        fields:
          - label: "Hero Quote 1"
            name: "hero_quote_1"
            widget: "string"
          - label: "Hero Text 1"
            name: "hero_text_1"
            widget: "text"
          - label: "Hero Quote 2"
            name: "hero_quote_2"
            widget: "string"
          - label: "Hero Text 2"
            name: "hero_text_2"
            widget: "text"
          - label: "Hero Quote 3"
            name: "hero_quote_3"
            widget: "string"
          - label: "Hero Text 3"
            name: "hero_text_3"
            widget: "text"
          - label: "Main Content Paragraph 1"
            name: "main_content_1"
            widget: "text"
          - label: "Main Content Paragraph 2"
            name: "main_content_2"
            widget: "text"
          - label: "Main Content Paragraph 3"
            name: "main_content_3"
            widget: "text"
          - label: "Main Content Paragraph 4"
            name: "main_content_4"
            widget: "text"
          - label: "Contact Phone"
            name: "contact_phone"
            widget: "string"
          - label: "Contact Email"
            name: "contact_email"
            widget: "string"
      - label: "Spanish Homepage"
        name: "spanish_index"
        file: "es/index.html"
        fields:
          - label: "Hero Quote 1"
            name: "hero_quote_1"
            widget: "string"
          - label: "Hero Text 1"
            name: "hero_text_1"
            widget: "text"
          - label: "Hero Quote 2"
            name: "hero_quote_2"
            widget: "string"
          - label: "Hero Text 2"
            name: "hero_text_2"
            widget: "text"
          - label: "Hero Quote 3"
            name: "hero_quote_3"
            widget: "string"
          - label: "Hero Text 3"
            name: "hero_text_3"
            widget: "text"
          - label: "Main Content Paragraph 1"
            name: "main_content_1"
            widget: "text"
          - label: "Main Content Paragraph 2"
            name: "main_content_2"
            widget: "text"
          - label: "Main Content Paragraph 3"
            name: "main_content_3"
            widget: "text"
          - label: "Main Content Paragraph 4"
            name: "main_content_4"
            widget: "text"
          - label: "Contact Phone"
            name: "contact_phone"
            widget: "string"
          - label: "Contact Email"
            name: "contact_email"
            widget: "string"
